### ISSUE TITLE
Index out of range

### ISSUE THREAD

**Issue by sabrehagen** [rusenask/keel#16]
Logs from an unsuccessful run:

```

2017-07-02T02:39:46.948903643Z time="2017-07-02T02:39:46Z" level=info msg="Keel starting.." arch=amd64 build_date=2017-07-01T135453Z go_version=go1.8.3 os=linux revision=2bb80bc version=2bb80bc 
2017-07-02T02:39:46.94955744Z time="2017-07-02T02:39:46Z" level=info msg="provider.kubernetes: using in-cluster configuration" 
2017-07-02T02:39:46.954138278Z time="2017-07-02T02:39:46Z" level=info msg="webhook trigger server starting..." port=9300 
2017-07-02T02:39:47.246839657Z time="2017-07-02T02:39:47Z" level=info msg="trigger.pubsub: subscribing for events..." subscription="keel-stemnapp-gcr.io%2Fstemnapp" topic="gcr.io%2Fstemnapp" 
2017-07-02T02:39:48.032452458Z time="2017-07-02T02:39:48Z" level=info msg="provider.kubernetes: processing event" repository="gcr.io/stemnapp/alpine-api" 
2017-07-02T02:39:48.032490719Z time="2017-07-02T02:39:48Z" level=warning msg="trigger.pubsub: failed to get name and version from image" action=INSERT error="Invalid Semantic Version" tag="gcr.io/stemnapp/alpine-api:latest" 
2017-07-02T02:39:48.045175015Z time="2017-07-02T02:39:48Z" level=info msg="provider.kubernetes: keel policy found, checking deployment..." labels=map[keel.observer/policy:all role:api] name=api namespace=default policy=all 
2017-07-02T02:39:48.045344518Z time="2017-07-02T02:39:48Z" level=info msg="provider.kubernetes: checking image" image="gcr.io/stemnapp/alpine-api" name=api namespace=default parsed_image_name="gcr.io/stemnapp/alpine-api" policy=all target_image_name="gcr.io/stemnapp/alpine-api" target_tag=v0.0.825 
2017-07-02T02:39:48.047617496Z panic: runtime error: index out of range
2017-07-02T02:39:48.04766674Z 
2017-07-02T02:39:48.047718926Z goroutine 10 [running]:
2017-07-02T02:39:48.047885113Z github.com/rusenask/keel/util/version.GetVersionFromImageName(0xc4206e2140, 0x1a, 0xc4201530e0, 0x1a, 0xc4203dd001)
2017-07-02T02:39:48.047974208Z 	/go/src/github.com/rusenask/keel/util/version/version.go:42 +0xa6
2017-07-02T02:39:48.04818757Z github.com/rusenask/keel/provider/kubernetes.(*Provider).impactedDeployments(0xc42032df80, 0xc4203d7920, 0xc420153230, 0x25, 0x25, 0xc420153230, 0xc4205a15c0)
2017-07-02T02:39:48.048282215Z 	/go/src/github.com/rusenask/keel/provider/kubernetes/kubernetes.go:178 +0xe43
2017-07-02T02:39:48.048464159Z github.com/rusenask/keel/provider/kubernetes.(*Provider).processEvent(0xc42032df80, 0xc4203d7920, 0x1, 0x1, 0xc4201531d0, 0xc420020f38, 0xc420020e98)
2017-07-02T02:39:48.048561704Z 	/go/src/github.com/rusenask/keel/provider/kubernetes/kubernetes.go:82 +0x4f
2017-07-02T02:39:48.048717174Z github.com/rusenask/keel/provider/kubernetes.(*Provider).startInternal(0xc42032df80, 0x7c9b4b, 0xc42004b980)
2017-07-02T02:39:48.048724565Z 	/go/src/github.com/rusenask/keel/provider/kubernetes/kubernetes.go:66 +0x27c
2017-07-02T02:39:48.048728564Z github.com/rusenask/keel/provider/kubernetes.(*Provider).Start(0xc42032df80, 0x20459e0, 0x0)
2017-07-02T02:39:48.048731942Z 	/go/src/github.com/rusenask/keel/provider/kubernetes/kubernetes.go:51 +0x2b
2017-07-02T02:39:48.048735349Z created by main.setupProviders
2017-07-02T02:39:48.048738529Z 	/go/src/github.com/rusenask/keel/main.go:111 +0xf9```

**Comment by rusenask** [comment]
There was a bug in version parsing, fixed it with https://github.com/rusenask/keel/pull/18. But there is another issue here - looks like your currently deployed image is untagged: `gcr.io/stemnapp/alpine-ap` should be something like `gcr.io/stemnapp/alpine-ap:v0.0.824`.

Furthermore, I am refactoring image parsing so it's a lot more robust.

**Comment by rusenask** [comment]
should be fixed in https://github.com/rusenask/keel/pull/26
